# version: '3'
services:
  nginx:
    image: 'nginx:alpine'
    ports:
      - '80:80'
    depends_on:
      - weather_app
    expose:
      - 80
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    
  weather_app:
    # image: 'weather_image:${TAG}'
    image: 'romi293/weather_app/weather_image:latest'
    build: 
      context: .
    command: 'sh -c "gunicorn --workers 3 --bind 0.0.0.0:5000 -m 007 wsgi:app"'
    expose:
      - 5000
    restart: always
    deploy:
      mode: replicated
      replicas: 2
