name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Git commit hash
        id: get_commit
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/weather_app:${{ env.TAG }}

      - name: Checkout second repository
        uses: actions/checkout@v2
        with:
          repository: Romi293/ArgoCD_Manifests
          token: ${{ secrets.GH_TOKEN }}
          path: argocd-manifests

      - name: Update Kubernetes manifest
        run: |
          sed -i 's|image: .*$|image: '"${{ secrets.DOCKERHUB_USERNAME }}/weather_app:${{ env.TAG }}"'|' deployment.yaml

      - name: Commit and push changes
        run: |
          cd argocd-manifests
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m 'Update Docker image to ${{ env.TAG }}'
          git push
